### ISSUE TITLE
ProxyClient.currentMap ne se met pas à jour lorsque le sniffing est désactivé

### ISSUE THREAD

**Issue by Merokai** [Aquazus/D1Proxy#9]
En essayant de faire un plugin je m’aperçois que ProxyClient.currentMap est toujours à 0.
Le problème est dans le GDMHandler qui met à jour la valeur de currentMap uniquement si le sniffing est activé.
Avec la possibilité de faire des plugins j'imagine que ce comportement n'est pas intentionnel.

**Comment by Aquazus** [comment]
Bien vu, je règle ça dans la journée !
